---

#non si usa proprio i was nel nostro caso, si usa soltanto W3SVC o iisreset /start



# To stop the web server, you must stop the Windows Process Activation Service (WAS) and the World Wide Web Publishing Service (W3SVC).



#----------------------------------------#
#             2- Stop IIS
#----------------------------------------#
- name: Stop IIS
  hosts: WindowsServer
  become: yes
  become_user: Administrator

  tasks:


    - name: Stop IIS
      ansible.windows.win_shell: iisreset /stop    #iisreset /restart  #net stop WAS #net start W3SVC

      register: stop_IIS

    - name: Stampa l'output del comando di stop IIS
      debug:
        var: stop_IIS.stdout_lines

    - name: Controlla che IIS è stato stoppato con successo
      debug:
        msg: "IIS è stato stoppato con successo"
      when: stop_IIS.rc == 0

    - name: Controlla che IIS non è stato stoppato
      fail:
        msg: "Errore: IIS non è stato stoppato"
      when: stop_IIS.rc != 0













#-----------------------------------------------------------------------------------------------

    # # # - name: Stop IIS
    # # #   ansible.windows.win_shell: net stop WAS     #iisreset /restart  #net stop WAS #net start W3SVC
    # # #   when: skip_task
    # # #   register: stop_IIS

    # # # - name: Stampa l'output del comando di stop IIS
    # # #   debug:
    # # #     var: stop_IIS.stdout_lines

    # # # - name: Controlla che IIS è stato stoppato con successo
    # # #   debug:
    # # #     msg: "IIS è stato stoppato con successo"
    # # #   when: stop_IIS.rc == 0

    # # # - name: Controlla che IIS non è stato stoppato
    # # #   fail:
    # # #     msg: "Errore: IIS non è stato stoppato"
    # # #   when: stop_IIS.rc != 0




# # # #----------------------------------------------------------------------------------------------


# # # - name: Stop and Start IIS and WAS services
# # #   hosts: windows_servers
# # #   tasks:
# # #     - name: Stop IIS service
# # #       win_service:
# # #         name: w3svc
# # #         state: stopped

# # #     - name: Stop WAS service
# # #       win_service:
# # #         name: WAS
# # #         state: stopped

    # - name: Start WAS service
    #   win_service:
    #     name: WAS
    #     state: started

    # - name: Start IIS service
    #   win_service:
    #     name: w3svc
    #     state: started







# Using a command line
# Open an elevated command-line window.

# At the command prompt, type net stop WAS and press ENTER; type Y and then press ENTER to stop W3SVC as well.

# To start the web server, type net start W3SVC and press ENTER to start both WAS and W3SVC.



# #----------------------------------------
# The following was tested for IIS 8.5 and Windows 8.1.

# As of IIS 7, Windows recommends restarting IIS via net stop/start. Via the command prompt (as Administrator):

# > net stop WAS
# > net start W3SVC
# net stop WAS will stop W3SVC as well. Then when starting, net start W3SVC will start WAS as a dependency.





# #----------------------------------------#
# IISRESET.EXE (c) Microsoft Corp. 1998-2005

# Usage:
# iisreset [computername]

#     /RESTART            Stop and then restart all Internet services.
#     /START              Start all Internet services.
#     /STOP               Stop all Internet services.
#     /REBOOT             Reboot the computer.
#     /REBOOTONERROR      Reboot the computer if an error occurs when starting,
#                         stopping, or restarting Internet services.
#     /NOFORCE            Do not forcefully terminate Internet services if
#                         attempting to stop them gracefully fails.
#     /TIMEOUT:val        Specify the timeout value ( in seconds ) to wait for
#                         a successful stop of Internet services. On expiration
#                         of this timeout the computer can be rebooted if
#                         the /REBOOTONERROR parameter is specified.
#                         The default value is 20s for restart, 60s for stop,
#                         and 0s for reboot.
#     /STATUS             Display the status of all Internet services.
#     /ENABLE             Enable restarting of Internet Services
#                         on the local system.
#     /DISABLE            Disable restarting of Internet Services
#                         on the local system.


